baseURL: https://adcondev.netlify.app/
title: AdConDev - Backend Developer
copyright: 'Copyright © 2023-{year} Adrián. All Rights Reserved.'
defaultContentLanguage: es
# hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.
# defaultContentLanguageInSubdir: true
# disableLanguages:
#  - fr
#  - zh-cn
#  - zh-tw
pagination:
  pagerSize: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

blackfriday:
  hrefTargetBlank: true

taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors

build:
  writeStats: false  # Desactivado para reducir uso de memoria
  noJSConfigInAssets: true
  useResourceCacheWhen: fallback

# Optimización de cache
caches:
  assets:
    dir: ":cacheDir/assets"
    maxAge: "24h"
  getcsv:
    dir: ":cacheDir/getcsv"
    maxAge: "1h"
  getjson:
    dir: ":cacheDir/getjson"
    maxAge: "1h"
  images:
    dir: ":cacheDir/images"
    maxAge: "24h"
  modules:
    dir: ":cacheDir/modules"
    maxAge: "24h"

permalinks:
  news: /news/:year/:month/:title/
  blog: /blog/:year/:month/:title/

module:
  imports:
    - path: github.com/hbstack/theme-cards
  # Optimización de proxy para China (si es necesario)
  # proxy: https://goproxy.cn

# services:
#   disqus:
#     shortname: your-disqus-shortname

markup:
  highlight:
    guessSyntax: true
    lineNos: true
    noClasses: false
    lineNumbersInTable: false
  goldmark:
    renderer:
      unsafe: true
    parser:
      wrapStandAloneImageWithinParagraph: false
      attribute:
        block: true
        title: true
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

# Suprimir advertencias menores
ignoreLogs: ['warning-goldmark-raw-html']
