# HB Stack Cards Theme Configuration
# sass_transpiler: 'dartsass' # Uncomment to use Dart Sass, you need to install Dart Sass first.

mainSections:
  - blog
  - posts
  - news

# titleSeparator: '|' # Title separator. Default to -.

description: Backend Developer especializado en automatización, APIs y desarrollo web
keywords: Golang, Python, Backend, FastAPI, Gin, GORM, Docker, CI/CD, GitHub Actions

logo: images/logo.webp # Logo image. Default to images/logo.webp.
brand: AdConDev

# HB Stack Cards specific configuration
hb:
  header:
    brand: AdConDev
    logo: images/logo.webp
    full_width: false
    sticky: true
    theme_toggle:
      style: switch
    search:
      expand: false  # Reducir carga inicial

  footer:
    powered_by: true

  blog:
    paginate: 6  # Reducido de 10 a 6 para menor uso de memoria
    post_date_format: ":date_long"
    post_thumbnail: true
    full_width: false
    toc:
      position: end
    home:
      pinned_posts_position: list

  docs:
    date_format: ":date_long"

# Theme and styling
theme:
  palette: purple
  color_mode: auto # light, dark or auto

# Math support (desactivado si no se usa)
math: false

# Optimizaciones de rendimiento
performance:
  lazy_loading: true
  optimize_images: true
  minify_css: true
  minify_js: true

# Configuración de imagen optimizada
imaging:
  resampleFilter: "Lanczos"
  quality: 85  # Reducido de 95 para menor uso de memoria
  anchor: "Smart"

# Table of contents
toc:
  enable: true
  position: content

# Breadcrumb
breadcrumb:
  enable: true

# Search
search:
  enable: true

# Social links
social:
  github: https://github.com/adcondev
  linkedin: https://linkedin.com/in/adrian-mazatlan
  email: adcondev@gmail.com

# Comment system (you can configure later)
# comments:
#   provider: giscus
