# Configuración del servidor Hugo optimizada para desarrollo
server:
  headers:
    - for: "/**"
      values:
        Cache-Control: "public, max-age=86400"

# Configuración de watch optimizada
watching:
  includePattern: "^(content|data|i18n|layouts|static|assets)/"
  excludePattern: "^(public|resources|node_modules|\\.git)/"

# Límites de memoria para desarrollo
limits:
  memory: "256MB"
  timeout: "30s"
